'use client';

import { useState, useEffect, useMemo } from 'react';
import Sidebar from './Sidebar';
import ClientSummarySection, { GhlTagLeadCounts } from './ClientSummarySection';
import FacebookStatsSection from './FacebookStatsSection';
import PMSAnalysisSection from './PMSAnalysisSection';
import FlagPanel from './FlagPanel';
import SyncPanel from './SyncPanel';
import PeriodOverviewSection from './PeriodOverviewSection';
import DataStatusPanel from './DataStatusPanel';
import { ProcessedData, ClientData } from '@/types';
import { loadManifest, loadPeriod, Manifest } from '@/lib/analysis/autoLoader';
import { computeCampaignRevenue } from '@/lib/analysis/campaignRevenue';
import { AlertCircle, Loader2, ChevronDown } from 'lucide-react';
import { Badge } from './ui/Badge';

export default function Dashboard() {
  const [manifest, setManifest] = useState<Manifest | null>(null);
  const [data, setData] = useState<ProcessedData | null>(null);
  const [selectedPeriodId, setSelectedPeriodId] = useState<string>('');
  const [selectedClient, setSelectedClient] = useState<string>('');
  const [activeView, setActiveView] = useState<'overview' | 'client'>('overview');

  function scrollToTop() {
    document.getElementById('main-scroll')?.scrollTo({ top: 0, behavior: 'instant' });
  }

  function goToClient(name: string) {
    setSelectedClient(name);
    setActiveView('client');
    scrollToTop();
  }
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  // Live GHL tag counts, keyed periodId -> clientName -> tag -> count.
  // Generated by scripts/sync-ghl-lead-counts.mts; optional (older checkouts
  // or environments without GHL creds simply show the placeholder cards).
  const [ghlLeadCounts, setGhlLeadCounts] = useState<Record<string, Record<string, GhlTagLeadCounts>> | null>(null);

  useEffect(() => {
    fetch('/data/ghl-lead-counts.json')
      .then((res) => (res.ok ? res.json() : null))
      .then((d) => setGhlLeadCounts(d?.periods ?? null))
      .catch(() => setGhlLeadCounts(null));
  }, []);

  useEffect(() => {
    loadManifest()
      .then((m) => {
        setManifest(m);
        if (m.periods.length > 0) setSelectedPeriodId(m.periods[0].id);
      })
      .catch((err) => setError(String(err)))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    if (!manifest || !selectedPeriodId) return;
    const period = manifest.periods.find((p) => p.id === selectedPeriodId);
    if (!period) return;

    setLoading(true);
    setError(null);
    setData(null);
    // Landing view for every period load (first load AND month switches) is
    // the Overview — switching months while inside a client would otherwise
    // dump you on the manifest's first client (currently Tàberg Falls).
    setActiveView('overview');
    scrollToTop();

    loadPeriod(period)
      .then((result) => {
        setData(result);
        // Default to first client in manifest order
        const firstClient = period.clients[0]?.name;
        if (firstClient && result.clients[firstClient]) {
          setSelectedClient(firstClient);
        } else {
          const first = Object.keys(result.clients)[0];
          if (first) setSelectedClient(first);
        }
      })
      .catch((err) => setError(String(err)))
      .finally(() => setLoading(false));
  }, [manifest, selectedPeriodId]);

  // Ordered client list: alphabetical, FB-only clients
  const orderedClients: ClientData[] = useMemo(() => {
    if (!data) return [];
    return Object.values(data.clients)
      .filter((c) => c.facebookStats != null)
      .sort((a, b) => a.name.localeCompare(b.name));
  }, [data]);

  const currentClient = data && selectedClient ? data.clients[selectedClient] : null;
  const clientFlags = data ? data.flags.filter((f) => f.clientName === selectedClient) : [];
  const currentPeriod = manifest?.periods.find((p) => p.id === selectedPeriodId);

  // Revenue attributed to each campaign type
  const campaignRevenue = useMemo(() => computeCampaignRevenue(currentClient), [currentClient]);

  const ghlTagLeads = ghlLeadCounts?.[selectedPeriodId]?.[selectedClient] ?? null;

  return (
    <div className="flex h-screen overflow-hidden">
      {/* Sidebar */}
      {!loading && !error && orderedClients.length > 0 && (
        <div className="bg-[var(--surface-strong)] border-r border-[var(--border)] flex flex-col overflow-hidden flex-shrink-0 w-[220px]">
          <Sidebar
            clients={orderedClients}
            selectedClient={activeView === 'client' ? selectedClient : ''}
            onSelectClient={(name) => goToClient(name)}
            periodLabel={currentPeriod?.label}
          />
        </div>
      )}

      {/* Main content */}
      <div className="flex-1 overflow-y-auto july-scrollbar" id="main-scroll">
        {/* Top bar */}
        {!loading && !error && data && (
          <div className="sticky top-0 z-10 bg-[var(--canvas-tint)]/85 backdrop-blur-sm border-b border-[var(--border)] px-8 py-3 flex items-center justify-between gap-4">
            {/* View tabs */}
            <div className="flex items-center gap-1">
              <button
                onClick={() => setActiveView('overview')}
                className={`px-3.5 py-2 text-[13px] font-semibold rounded-[10px] transition-colors duration-150 ${activeView === 'overview' ? 'bg-[var(--brand)] text-white' : 'text-[var(--muted)] hover:text-[var(--foreground)] hover:bg-[var(--fill-cool)]'}`}
              >
                Overview
              </button>
              <button
                onClick={() => setActiveView('client')}
                className={`flex items-center gap-2 px-3.5 py-2 text-[13px] font-semibold rounded-[10px] transition-colors duration-150 ${activeView === 'client' ? 'bg-[var(--brand)] text-white' : 'text-[var(--muted)] hover:text-[var(--foreground)] hover:bg-[var(--fill-cool)]'}`}
              >
                {activeView === 'client' && currentClient ? (
                  <>
                    {selectedClient}
                    <div className="flex gap-1">
                      {currentClient.facebookStats && <Badge variant="info">Facebook</Badge>}
                      {currentClient.pmsAnalysis && <Badge variant="success">PMS</Badge>}
                      {currentClient.hasGHL && <Badge variant="neutral">GHL</Badge>}
                    </div>
                    {clientFlags.length > 0 && <Badge variant="warning">{clientFlags.length} flag{clientFlags.length !== 1 ? 's' : ''}</Badge>}
                  </>
                ) : 'Client View'}
              </button>
            </div>

            {/* Period selector (only if multiple periods) */}
            {manifest && manifest.periods.length > 1 && (
              <div className="relative">
                <select
                  value={selectedPeriodId}
                  onChange={(e) => setSelectedPeriodId(e.target.value)}
                  className="appearance-none text-[13px] font-semibold border border-[var(--border-strong)] rounded-[12px] pl-4 pr-9 py-2 bg-[var(--surface-strong)] text-[var(--foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--brand)] shadow-[0_2px_12px_rgba(15,23,42,.04)]"
                >
                  {manifest.periods.map((p) => (
                    <option key={p.id} value={p.id}>{p.label}</option>
                  ))}
                </select>
                <ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-[var(--muted-soft)]" />
              </div>
            )}
          </div>
        )}

        {/* Overview tab */}
        {!loading && !error && data && activeView === 'overview' && (
          <PeriodOverviewSection
            manifestClients={currentPeriod?.clients ?? []}
            data={data}
            onSelectClient={(name) => goToClient(name)}
          />
        )}

        <div className="px-8 py-8 max-w-5xl space-y-6">
          {/* Loading */}
          {loading && (
            <div className="flex flex-col items-center justify-center py-40 gap-4">
              <Loader2 className="w-7 h-7 text-[var(--muted-soft)] animate-spin" />
              <p className="text-[13px] text-[var(--muted-soft)]">
                {!manifest ? 'Loading data...' : `Processing ${currentPeriod?.label ?? 'data'}...`}
              </p>
            </div>
          )}

          {/* Error */}
          {error && !loading && (
            <div className="max-w-lg p-6 bg-[rgba(220,38,38,.06)] border border-[rgba(220,38,38,.18)] rounded-[16px] flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-[var(--danger)] flex-shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold text-[var(--danger)] text-[13px]">Failed to load data</p>
                <p className="text-[13px] text-[var(--danger)]/80 mt-1">{error}</p>
              </div>
            </div>
          )}

          {/* Client content */}
          {!loading && !error && currentClient && activeView === 'client' && (
            <>
              {/* Data status diagnostics */}
              <DataStatusPanel
                hasPMS={currentClient.hasPMS}
                hasGHL={currentClient.hasGHL}
                flags={clientFlags}
              />

              {/* Summary bar */}
              <ClientSummarySection
                facebookStats={currentClient.facebookStats}
                pmsSummary={currentClient.pmsAnalysis?.summary ?? null}
                campaignRevenue={campaignRevenue}
                instagramLeads={currentClient.pmsAnalysis?.instagram ?? null}
                facebookLeads={currentClient.pmsAnalysis?.facebook ?? null}
                ghlTagLeads={ghlTagLeads}
              />

              {currentClient.facebookStats && (
                <FacebookStatsSection
                  key={selectedClient}
                  stats={currentClient.facebookStats}
                  campaignRevenue={campaignRevenue}
                  instagramLeads={currentClient.pmsAnalysis?.instagram ?? null}
                  facebookLeads={currentClient.pmsAnalysis?.facebook ?? null}
                  avgDirectBookingValue={currentClient.pmsAnalysis?.summary.avgDirectBookingValue}
                />
              )}

              {currentClient.pmsAnalysis && (
                <PMSAnalysisSection
                  analysis={currentClient.pmsAnalysis}
                  facebookStats={currentClient.facebookStats}
                />
              )}

              {!currentClient.facebookStats && !currentClient.pmsAnalysis && (
                <div className="rounded-[16px] border border-dashed border-[var(--border-strong)] px-8 py-16 text-center">
                  <p className="text-[13px] text-[var(--muted-soft)]">No data available for this client.</p>
                </div>
              )}

              {/* Per-client flags */}
              {clientFlags.length > 0 && <FlagPanel flags={clientFlags} />}
            </>
          )}

          <SyncPanel />
        </div>
      </div>
    </div>
  );
}
