'use client';

import { useState, useEffect, useMemo } from 'react';
import Sidebar from './Sidebar';
import ClientSummarySection from './ClientSummarySection';
import FacebookStatsSection from './FacebookStatsSection';
import PMSAnalysisSection from './PMSAnalysisSection';
import FlagPanel from './FlagPanel';
import PeriodOverviewSection from './PeriodOverviewSection';
import DataStatusPanel from './DataStatusPanel';
import { ProcessedData, ClientData } from '@/types';
import { computeCampaignRevenue } from '@/lib/analysis/campaignRevenue';
import { AlertCircle, Loader2 } from 'lucide-react';
import { Badge } from './ui/Badge';

interface ManifestClient {
  name: string;
  pms?: string;
  ghl?: string;
}
interface SnapshotPeriod {
  id: string;
  label: string;
  clients: ManifestClient[];
}
interface Snapshot {
  period: SnapshotPeriod;
  data: ProcessedData;
}

// Frozen reference view: renders a hardcoded snapshot (public/data/snapshots/july-2026.json,
// generated by scripts/snapshot-period.mts) instead of live-computing from the sync
// pipeline. Intentional — this is a fixed point-in-time view that won't shift while
// the live dashboard's analysis logic keeps changing.
export default function JulyDashboard() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [selectedClient, setSelectedClient] = useState<string>('');
  const [activeView, setActiveView] = useState<'overview' | 'client'>('overview');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  function scrollToTop() {
    document.getElementById('main-scroll')?.scrollTo({ top: 0, behavior: 'instant' });
  }

  function goToClient(name: string) {
    setSelectedClient(name);
    setActiveView('client');
    scrollToTop();
  }

  useEffect(() => {
    fetch('/data/snapshots/july-2026.json')
      .then((res) => {
        if (!res.ok) throw new Error(`Could not load July snapshot (${res.status})`);
        return res.json();
      })
      .then((snap: Snapshot) => {
        setSnapshot(snap);
        const firstClient = snap.period.clients[0]?.name;
        if (firstClient && snap.data.clients[firstClient]) {
          setSelectedClient(firstClient);
        } else {
          const first = Object.keys(snap.data.clients)[0];
          if (first) setSelectedClient(first);
        }
      })
      .catch((err) => setError(String(err)))
      .finally(() => setLoading(false));
  }, []);

  const data = snapshot?.data ?? null;

  const orderedClients: ClientData[] = useMemo(() => {
    if (!data) return [];
    return Object.values(data.clients)
      .filter((c) => c.facebookStats != null || c.pmsAnalysis != null)
      .sort((a, b) => a.name.localeCompare(b.name));
  }, [data]);

  const currentClient = data && selectedClient ? data.clients[selectedClient] : null;
  const clientFlags = data ? data.flags.filter((f) => f.clientName === selectedClient) : [];

  const campaignRevenue = useMemo(() => computeCampaignRevenue(currentClient), [currentClient]);

  return (
    <div className="flex h-screen bg-[#f8f8f7] overflow-hidden">
      {/* Sidebar */}
      {!loading && !error && orderedClients.length > 0 && (
        <div className="bg-white border-r border-gray-100 flex flex-col overflow-hidden flex-shrink-0 w-[220px]">
          <Sidebar
            clients={orderedClients}
            selectedClient={activeView === 'client' ? selectedClient : ''}
            onSelectClient={(name) => goToClient(name)}
            periodLabel={snapshot?.period.label}
          />
        </div>
      )}

      {/* Main content */}
      <div className="flex-1 overflow-y-auto" id="main-scroll">
        {/* Top bar */}
        {!loading && !error && data && (
          <div className="sticky top-0 z-10 bg-[#f8f8f7]/90 backdrop-blur-sm border-b border-gray-100 px-8 py-3 flex items-center justify-between gap-4">
            <div className="flex items-center gap-1">
              <button
                onClick={() => setActiveView('overview')}
                className={`px-3 py-1.5 text-sm font-medium rounded-lg transition-colors ${activeView === 'overview' ? 'bg-gray-900 text-white' : 'text-gray-500 hover:text-gray-700'}`}
              >
                Overview
              </button>
              <button
                onClick={() => setActiveView('client')}
                className={`flex items-center gap-2 px-3 py-1.5 text-sm font-medium rounded-lg transition-colors ${activeView === 'client' ? 'bg-gray-900 text-white' : 'text-gray-500 hover:text-gray-700'}`}
              >
                {activeView === 'client' && currentClient ? (
                  <>
                    {selectedClient}
                    <div className="flex gap-1">
                      {currentClient.facebookStats && <Badge variant="info">Facebook</Badge>}
                      {currentClient.pmsAnalysis && <Badge variant="success">PMS</Badge>}
                      {currentClient.hasGHL && <Badge variant="neutral">GHL</Badge>}
                    </div>
                    {clientFlags.length > 0 && <Badge variant="warning">{clientFlags.length} flag{clientFlags.length !== 1 ? 's' : ''}</Badge>}
                  </>
                ) : 'Client View'}
              </button>
            </div>

            {/* Fixed period badge — no selector; this view is locked to July 2026 */}
            <span className="text-sm font-medium border border-gray-200 rounded-xl px-4 py-2 bg-white text-gray-700 shadow-sm">
              {snapshot?.period.label} <span className="text-gray-400">(frozen snapshot)</span>
            </span>
          </div>
        )}

        {/* Overview tab */}
        {!loading && !error && data && activeView === 'overview' && (
          <PeriodOverviewSection
            manifestClients={snapshot?.period.clients ?? []}
            data={data}
            onSelectClient={(name) => goToClient(name)}
          />
        )}

        <div className="px-8 py-8 max-w-5xl space-y-6">
          {/* Loading */}
          {loading && (
            <div className="flex flex-col items-center justify-center py-40 gap-4">
              <Loader2 className="w-7 h-7 text-gray-300 animate-spin" />
              <p className="text-sm text-gray-400">Loading July snapshot...</p>
            </div>
          )}

          {/* Error */}
          {error && !loading && (
            <div className="max-w-lg p-6 bg-red-50 border border-red-100 rounded-2xl flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold text-red-700 text-sm">Failed to load July snapshot</p>
                <p className="text-sm text-red-500 mt-1">{error}</p>
              </div>
            </div>
          )}

          {/* Client content */}
          {!loading && !error && currentClient && activeView === 'client' && (
            <>
              <DataStatusPanel
                hasPMS={currentClient.hasPMS}
                hasGHL={currentClient.hasGHL}
                flags={clientFlags}
              />

              <ClientSummarySection
                facebookStats={currentClient.facebookStats}
                pmsSummary={currentClient.pmsAnalysis?.summary ?? null}
                campaignRevenue={campaignRevenue}
                instagramLeads={currentClient.pmsAnalysis?.instagram ?? null}
                facebookLeads={currentClient.pmsAnalysis?.facebook ?? null}
              />

              {currentClient.facebookStats && (
                <FacebookStatsSection
                  key={selectedClient}
                  stats={currentClient.facebookStats}
                  campaignRevenue={campaignRevenue}
                  instagramLeads={currentClient.pmsAnalysis?.instagram ?? null}
                  facebookLeads={currentClient.pmsAnalysis?.facebook ?? null}
                  avgDirectBookingValue={currentClient.pmsAnalysis?.summary.avgDirectBookingValue}
                />
              )}

              {currentClient.pmsAnalysis && (
                <PMSAnalysisSection
                  analysis={currentClient.pmsAnalysis}
                  facebookStats={currentClient.facebookStats}
                />
              )}

              {!currentClient.facebookStats && !currentClient.pmsAnalysis && (
                <div className="rounded-2xl border border-dashed border-gray-200 px-8 py-16 text-center">
                  <p className="text-sm text-gray-400">No data available for this client.</p>
                </div>
              )}

              {clientFlags.length > 0 && <FlagPanel flags={clientFlags} />}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
